### ISSUE TITLE
Static class

### ISSUE THREAD

**Issue by playmono** [timemachine3030/safe-url#2]
Hi,

I made the class static for better usaging (SafeUrl::makeUrl($url))

https://github.com/playmono/safe-url

**Comment by timemachine3030** [comment]
Makes sense to me! can you update the tests and make a pull request?

**Comment by playmono** [comment]
@timemachine3030 I did the PR already. Is there any problem?

**Comment by timemachine3030** [comment]
So Sorry, I didn't get the notification from GitHub.  I have merged the PR

**Comment by playmono** [comment]
@timemachine3030 It's fine. Btw I noticed I coded this commit in this way: "static public function", and I usually do "public static function". I dont know which is better talking about good coding practices.

Anyway, code still works.
